### ISSUE TITLE
GLCFS Point Query tool; internal server error

### ISSUE THREAD

**Issue by beckypearson** [glos/user_queries#31]
Good morning,

I'm trying to download wave data for a point in Lake Michigan. This offshore wave data is of very importance since I will use the information to help calibrate a nearshore wave model. I've been able to do this in the past using the GLCFS Point Query tool, however, when I try to download data for my required period of time (11/06/17 - 01/05/18), it tells me the server encountered an internal error that prevented it from fulfilling the request (see error at the end of the email). 

Would it be possible to get the wave data from another source? Is there something I can do differently to avoid this error? I'd really appreciate any kind of help you can provide me.

Thanks in advance and have a wonderful day!

Best regards,
Alejandra Lira

HTTP Status 500 - opendap.dap.DataReadException: Inconsistent array length read: 1165128303 != 1914731274
type Exception report

message opendap.dap.DataReadException: Inconsistent array length read: 1165128303 != 1914731274

description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.io.IOException: opendap.dap.DataReadException: Inconsistent array length read: 1165128303 != 1914731274
ucar.nc2.dods.DODSNetcdfFile.readData(DODSNetcdfFile.java:1662)
ucar.nc2.Variable.reallyRead(Variable.java:879)
ucar.nc2.Variable._read(Variable.java:865)
ucar.nc2.Variable.read(Variable.java:677)
ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:553)
ucar.nc2.dataset.VariableDS._read(VariableDS.java:533)
ucar.nc2.Variable.read(Variable.java:677)
ucar.nc2.Variable.read(Variable.java:651)
us.glos.glcfs.serlvet.GLCFSPointSourceServlet.doGet(GLCFSPointSourceServlet.java:429)
javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
org.glc.StartPoint.doFilter(StartPoint.java:55)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.57 logs.

**Comment by kkoch** [comment]
I've submitted an issue for this. I was able to replicate for Michigan and Erie.  The other 3 lakes appear to work fine.

**Comment by kkoch** [comment]
@beckypearson Can you shoot me Alejandra's email - I'd like to get the specifics of what she's looking for so that @tslawecki can get her the data while we are troubleshooting the issue.

**Comment by beckypearson** [comment]
@kkoch  The email is alejandra.lira@smithgroupjjr.com

**Comment by cheryldmorse** [comment]
@tslawecki  - I think it's probably related. 
The following error keeps appearing in the logs:

2018-01-16T18:35:32.944 +0000 [ 623317371][ 4289229] ERROR - thredds.server.opendap.OpendapServlet - path2= /glos/glcfs/archive2016/michigan/ncas_his2d.dods
java.lang.IllegalStateException: DataBTree doesnt start with TREE
        at ucar.nc2.iosp.hdf5.DataBTree$Node.<init>(DataBTree.java:175) ~[cdm-4.6.5.jar:4.6.5]
        at ucar.nc2.iosp.hdf5.DataBTree$DataChunkIterator.<init>(DataBTree.java:135) ~[cdm-4.6.5.jar:4.6.5]
        at ucar.nc2.iosp.hdf5.DataBTree.getDataChunkIteratorFilter(DataBTree.java:61) ~[cdm-4.6.5.jar:4.6.5]
        at ucar.nc2.iosp.hdf5.H5tiledLayoutBB.<init>(H5tiledLayoutBB.java:110) ~[cdm-4.6.5.jar:4.6.5]
        at ucar.nc2.iosp.hdf5.H5iosp.readData(H5iosp.java:162) ~[cdm-4.6.5.jar:4.6.5]

The following TDS issue sounds like what we are seeing:: https://github.com/Unidata/thredds/issues/518
The issue is fixed in the newer versions of TDS

**Comment by kkoch** [comment]
Bandaid in place (@gcutrell will be rebooting the server twice a day until the real resolution is in place). I've emailed Alejandra.

**Comment by kkoch** [comment]
Alejandra is still having issues but trying to nail down some more specifics since it seems to be working for me.  I did send her downloads for three points she was looking for (for the above date range) as well as specific instructions on the tool.

Point1: Longitude: -87.76 Latitude: 42.32
Point2: Longitude: -87.72 Latitude: 42.44
Point3: Longitude: -87.76 Latitude: 42.52

**Comment by gcutrell** [comment]
@kkoch Are you and Alejandra using the same query? If yours is working maybe she should clear her browser cache.
